### ISSUE TITLE
Compatibility issues with multiple extensions

### ISSUE THREAD

**Issue by iamdarkle** [blomstra/flarum-ext-fontawesome#1]
I posted a issue on Clark's extension (https://github.com/clarkwinkelmann/flarum-pages-generator/issues/2) thinking it would be on his side, but it looks like that's not the case, he has taken the time to take a look at what's going on.

Quoting Clark's message about the issue:

> The problem lies with the FontAwesome extension. It resolves `UrlGenerator` too early in a service provider, causing all extensions enabled after itself to be unable to register new routes https://github.com/blomstra/flarum-ext-fontawesome/blob/master/src/Providers/FontAwesomePreloads.php
> 
> Usually this can be worked around by disabling and re-enabling extensions in a new order, but since root `extend.php` extenders always run last, there is no workaround until this gets fixed in the Blomstra extension.

I'm having trouble with these extensions so far:
- `clarkwinkelmann/flarum-pages-generator`
- `acpl/flarum-lscache`

I have a couple of other problems but I haven't yet found the extension that is causing the whole thing, but I guess it's all for the same reason.

**Comment by davwheat** [comment]
Fixed in 14c55e5a3b0a6eff1e0229eaed3e90c84e40e71c

Version 0.1.1 tagged :)
